version: '3.9'

services:

  db:
    image: postgres:latest
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    build:
      context: .
    command: >
      sh -c "python src/manage.py makemigrations &&
             python src/manage.py migrate &&
             python src/manage.py collectstatic --no-input &&
             cd src/ &&
             gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers=4 --timeout=300 --log-level=debug &&
             cd .."
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - .:/app
      - static:/app/src/static
      - media:/app/src/media
    depends_on:
      - db
  nginx:
    build: ./nginx
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - static:/app/src/static
      - media:/app/src/media
    depends_on:
      - web

volumes:
  pg_data:
  static:
  media:

