# Generated by Django 4.2.1 on 2023-05-10 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DateField(auto_now_add=True)),
                ('users', models.ManyToManyField(related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
