# Generated by Django 4.2.1 on 2023-05-10 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
