# Generated by Django 4.2.1 on 2023-05-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('volume', models.FloatField(default=0.0)),
                ('payment_amount', models.FloatField(default=0.0)),
            ],
        ),
    ]
