# Generated by Django 4.2.1 on 2023-06-01 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_paymentstatus_payment_staff_product_payment_status'),
        ('trucks', '0003_alter_truck_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='payment_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='orders.paymentstatus'),
        ),
        migrations.CreateModel(
            name='TruckPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(default=0.0)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truck_payments', to='trucks.truck')),
            ],
        ),
    ]
