# Generated by Django 4.2.1 on 2023-05-16 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
        ('orders', '0004_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='trucks.truck'),
        ),
    ]
